---
- name: vSphere VM automation through Template
  hosts: localhost
  become: false
  gather_facts: true
  collections:
    - community.vmware
  tasks:
    - name: Create new VM from template
      tags:
        - vmDeployAutomated
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        datacenter: "{{ vcenter_datacenter }}"
        cluster: "{{ vcenter_cluster }}"
        folder: "{{ vcenter_dest_folder }}"
        name: "{{ guest_hostname }}"
        annotation: "{{ vm_annotation }}"
        template: "{{ vm_template }}"
        disk:
          - datastore: "{{ vm_disk_datastore }}"
            size_gb: "{{ vm_disk_size_gb }}"
        networks:
          - name: "{{ vm_vlan_net }}"
            type: static
            ip: "{{ ipv4addr }}"
            netmask: "{{ vm_net_mask }}"
            gateway: "{{ vm_net_gw }}"
            start_connected: True
        hardware:
          memory_mb: "{{ vm_hw_mem_mb }}"
          num_cpus: "{{ vm_hw_cpu_n }}"
          scsi: paravirtual
        customization:
          hostname: "{{ guest_hostname }}"
          domain: "{{ guest_domain }}"
          dns_servers: "{{ dns_servers }}"
          dns_suffix: "{{ dns_suffix }}"
        state: poweredon
      register: static_vm
